### ISSUE TITLE
Why no RSS anymore?

### ISSUE THREAD

**Issue by ScreenDriver** [Legitcode/ReactJSNews#3]
Why was the RSS feed at https://reactjsnews.com/rss/ removed?

**Comment by zackify** [comment]
I will set that up for you, didn't mean to remove it, just got forgotten
during the transition.

**Comment by ScreenDriver** [comment]
Thank you :+1: 
RSS feeds are one of the greates internet inventions but unfortunately no one use it.

**Comment by skevy** [comment]
@zackify maybe we can use this? https://github.com/snaptortoise/jekyll-rss-feeds

**Comment by zackify** [comment]
I'll set that up tonight!

**Comment by zackify** [comment]
so it was there the whole time, just no link in the head :P https://reactjsnews.com/feed.xml fixed though!

**Comment by ScreenDriver** [comment]
Thank you very much :+1:
